### ISSUE TITLE
SUBTLETY - folder organization

### ISSUE THREAD

**Issue by franfranfranfran** [mpreedy/prj-rev-bwfs-dasmoto#1]
https://github.com/mpreedy/prj-rev-bwfs-dasmoto/tree/master/ArtsCrafts/resources

nice work creating the resources folder to help keep your project directory organized. css is also a resource so it should go inside there as well. inside of resources you can have two separate folders - one for css and one for images.

**Comment by mpreedy** [comment]
Got it!
