### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [mpreedy/prj-rev-bwfs-dasmoto#2]
https://github.com/mpreedy/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/index.html#L7

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found here - https://www.w3schools.com/html/html_entities.asp

**Comment by mpreedy** [comment]
Ok, so when it comes to symbols it'd be better to use the HTML entities so they don't get confused with the code. This is really useful information!
