### ISSUE TITLE
SIMPLIFY - dry css

### ISSUE THREAD

**Issue by franfranfranfran** [mpreedy/prj-rev-bwfs-dasmoto#3]
https://github.com/mpreedy/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/style.css#L3
https://github.com/mpreedy/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/style.css#L18
etc...

try to keep in mind dry principles when setting your css. are there any elements on the page that should not receive the helvetica font-family? can you set this styling just once for the entire page?

**Comment by mpreedy** [comment]
This makes sense. Thank you.
