### ISSUE TITLE
IMPORTANT - div vs span

### ISSUE THREAD

**Issue by franfranfranfran** [mpreedy/prj-rev-bwfs-dasmoto#4]
https://github.com/mpreedy/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/index.html#L25-L26

consider using span to style items within a line of text instead of the div. this is exactly what the span is built for! check out more info here - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span

**Comment by mpreedy** [comment]
This makes perfect sense! I was having a difficult time getting the text within the span to be on the same line. I don't think they covered that element within our courses! Thank you!
