### ISSUE TITLE
IMPORTANT - css selectors

### ISSUE THREAD

**Issue by franfranfranfran** [mpreedy/prj-rev-bwfs-dasmoto#5]
make sure you are targeting the elements that you want to style with your css selectors. take a look at your page and the size of the fonts for all of the headers. they look a bit bigger than they should be given the font-size you are providing. this is because you should target the h1 elements directly to set the font-size.

also, try using other h elements like h3 or h4 to represent the less important header elements. more info can be found here - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

**Comment by mpreedy** [comment]
This helps tremendously! I could not figure out why the font was so large! Thanks! Instead of using the #title selector I should have just used the h1 selector in CSS.
