### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [mpreedy/prj-rev-bwfs-dasmoto#7]
**GRADE**: Needs Improvement

**SUMMARY**: Nice start on this project! With some tweaks, the site itself will be looking great. Good call using divs to help organize the content on the page, just make sure to keep in mind the relationship between elements and sections on the page and use divs to help reinforce those relationships. 

Behind the scenes in the css, make sure to keep in mind DRY principles. Try to avoid repeatedly setting the same styling for similar elements wherever possible. Also, be sure you are targeting the correct elements in your css, compare your project to the example pages to confirm that your styling is taking effect. Clean, concise code is crucial and only becomes more so as your projects grow in size and complexity.

As a next step, try to restructure your code with the above tips in mind.

Keep up the good work!

**Comment by mpreedy** [comment]
Thank you for the feedback. I will continue to look at these elements and keep them in mind.
